server:
  interface: 10.64.0.1
  port: 53
  access-control: 10.64.0.0/24 allow
  verbosity: 0
  logfile: ""
  use-syslog: no
  log-queries: no
  log-replies: no
  hide-identity: yes
  hide-version: yes
  qname-minimisation: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  auto-trust-anchor-file: "/var/lib/unbound/root.key"

